<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <AnalysisMode>Default</AnalysisMode>
    <EnableNUnitRunner>true</EnableNUnitRunner>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ShipTests\TestData\NewFile1.txt" />
    <None Remove="ShipTests\TestData\SKILLS_BY_TIER.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="7.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.2" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.3.2" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.0.2" />
    <PackageReference Include="NUnit" Version="4.4.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataConverter\DataConverter.csproj" />
    <ProjectReference Include="..\WowsShipBuilder.GameParamsExtractor\WowsShipBuilder.GameParamsExtractor.csproj" />
  </ItemGroup>

</Project>
