// <auto-generated />

using System.Collections.Generic;

namespace DataConverter.WGStructure
{
    public class WGAircraft
    {
        public double attackCooldown { get; set; }
        public int attackCount { get; set; }
        public int attackInterval { get; set; }
        public double attackSpeedMultiplier { get; set; }
        public double attackSpeedMultiplierApplyTime { get; set; }
        public double attackerDamageTakenMultiplier { get; set; }
        public int attackerSize { get; set; }
        public double bombFallingTime { get; set; }
        public string bombName { get; set; }
        public double damageTakenMultiplier { get; set; }
        public double flightHeight { get; set; }
        public double flightRadius { get; set; }
        public Hangarsettings hangarSettings { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public double innerBombsPercentage { get; set; }
        public List<double> innerSalvoSize { get; set; }
        public bool isAirSupportPlane { get; set; }
        public bool isConsumablePlane { get; set; }
        public bool isJatoBoosterDetachable { get; set; }
        public double jatoDuration { get; set; }
        public double jatoSpeedMultiplier { get; set; }
        public int maxHealth { get; set; }
        public string name { get; set; }
        public double naturalAcceleration { get; set; }
        public double naturalDeceleration { get; set; }
        public int numPlanesInSquadron { get; set; }
        public float returnHeight { get; set; }
        public float speedMax { get; set; }
        public float speedMin { get; set; }
        public float speedMoveWithBomb { get; set; }
        public Typeinfo typeinfo { get; set; }
    }

    public class Hangarsettings
    {
        public int maxValue { get; set; }
        public int restoreAmount { get; set; }
        public int startValue { get; set; }
        public float timeToRestore { get; set; }
    }
}
