// <auto-generated />
namespace DataConverter.WGStructure
{
    public class WGAircraft
    {
        public Hangarsettings hangarSettings { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public int maxHealth { get; set; }
        public string name { get; set; }
        public int numPlanesInSquadron { get; set; }
        public float returnHeight { get; set; }
        public float speedMax { get; set; }
        public float speedMin { get; set; }
        public float speedMoveWithBomb { get; set; }
        public Typeinfo typeinfo { get; set; }
    }

    public class Hangarsettings
    {
        public int maxValue { get; set; }
        public int restoreAmount { get; set; }
        public int startValue { get; set; }
        public float timeToRestore { get; set; }
    }
}
