// <auto-generated />
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using JsonSubTypes;
using WoWsShipBuilder.DataStructures;

namespace DataConverter.WGStructure
{

    public class WGCaptain
    {
        public CrewPersonality CrewPersonality { get; set; }
        public Dictionary<string, WGSkill> Skills { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public string name { get; set; }
        public Typeinfo typeinfo { get; set; }
        public Dictionary<string, WGUniqueSkill> uniqueSkills { get; set; }
    }

    public class CrewPersonality
    {
        public bool canResetSkillsForFree { get; set; }
        public List<string> tags { get; set; }
        public string personName { get; set; }
    }

    //big skill structure. modifiers contain always on effects.
    public class WGSkill
    {
        public SkillTrigger LogicTrigger { get; set; }
        public bool canBeLearned { get; set; }
        public bool isEpic { get; set; }
        public Dictionary<string, JToken> modifiers { get; set; } // either a float or a ModifiersPerClass object
        //this is actually the skill number
        public int skillType { get; set; }
    }

    //these are populated when the skill has a condition to trigger.
    //modifiers are the modifiers applied when the condition is met.
    //Condition defined by triggerType and triggerDescIds ?
    public class SkillTrigger
    {
        public int burnCount { get; set; }
        public float changePriorityTargetPenalty { get; set; }
        public string consumableType { get; set; }
        public float coolingDelay { get; set; }
        public object[] coolingInterpolator { get; set; }
        public string dividerType { get; set; }
        public float dividerValue { get; set; }
        public float duration { get; set; }
        public float energyCoeff { get; set; }
        public int floodCount { get; set; }
        public object[] heatInterpolator { get; set; }
        public Dictionary<string, float> modifiers { get; set; }
        public string triggerDescIds { get; set; }
        public string triggerType { get; set; }
    }

     public class WGUniqueSkill
    {
        public int maxTriggerNum { get; set; }
        public ShipClass[] triggerAllowedShips { get; set; }
        public string triggerType { get; set; }

        [JsonExtensionData]
        public Dictionary<string, JToken> skillEffects { get; set; } // value is actually Dictionary<string, object>, process in converter
    }
}
