// <auto-generated />
using System.Collections.Generic;

namespace DataConverter.WGStructure
{

    public class Rootobject
    {
        public long id { get; set; }
        public string index { get; set; }
        public string name { get; set; }
        public Typeinfo typeinfo { get; set; }
        public Dictionary<string,Statistics> variants { get; set; }
    }

    public class Statistics
    {
        public string descIDs { get; set; }
        public string group { get; set; }
        public string iconIDs { get; set; }
        public int numConsumables { get; set; }
        public float reloadTime { get; set; }
        public float workTime { get; set; }
    }
        

}
