// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace DataConverter.WGStructure
{

    public class WGConsumable
    {
        public long id { get; set; }
        public string index { get; set; }
        public string name { get; set; }
        public Typeinfo typeinfo { get; set; }
        public Dictionary<string,Statistics> variants { get; set; }
    }

    public class Statistics
    {
        public string descIDs { get; set; }
        public string group { get; set; }
        public string iconIDs { get; set; }
        public int numConsumables { get; set; }
        public float reloadTime { get; set; }
        public float workTime { get; set; }
        
        [JsonExtensionData]
        public Dictionary<string, JToken> RawEffects { get; set; }

        [JsonIgnore]
        public Dictionary<string, float> Effects => RawEffects
            ?.Select(entry => (entry.Key, Value: entry.Value.ToObject<float>()))
            ?.ToDictionary(entry => entry.Key, entry => entry.Value);
    }
        

}
