// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataConverter.WGStructure
{

    public class WGModule
    {
        public int costCR { get; set; }
        public int costXP { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public string name { get; set; }
        public Typeinfo typeinfo { get; set; }
    }

}
