// <auto-generated />

namespace DataConverter.WGStructure
{
    public class WGModule : WGObject
    {
        public int costCR { get; set; }
        public int costXP { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public string name { get; set; }
    }

}
