// <auto-generated />
using JsonSubTypes;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataConverter.WGStructure
{
    [JsonConverter(typeof(JsonSubtypes), "typeinfo.species")]
    [JsonSubtypes.KnownSubType(typeof(WGShell), "Artillery")]
    [JsonSubtypes.KnownSubType(typeof(WGBomb), "Bomb")]
    [JsonSubtypes.KnownSubType(typeof(WGBomb), "SkipBomb")]
    [JsonSubtypes.KnownSubType(typeof(WGTorpedo), "Torpedo")]
    [JsonSubtypes.KnownSubType(typeof(WGDepthCharge), "DepthCharge")]
    [JsonSubtypes.KnownSubType(typeof(WGRocket), "Rocket")]
    public class WGProjectile : WGObject
    {
        public long id { get; set; }
        public string index { get; set; }
        public string name { get; set; }
    }


    public class WGShell : WGProjectile
    {
        public bool affectedByPTZ { get; set; }
        public float alphaDamage { get; set; }
        public float alphaPiercingCS { get; set; }
        public float alphaPiercingHE { get; set; }
        public string ammoType { get; set; }
        public bool applyPTZCoeff { get; set; }
        public float bulletAirDrag { get; set; }
        public float bulletDetonator { get; set; }
        public float bulletDetonatorThreshold { get; set; }
        public float bulletDiametr { get; set; }
        public float bulletKrupp { get; set; }
        public float bulletMass { get; set; }
        public float bulletRicochetAt { get; set; }
        public float bulletAlwaysRicochetAt { get; set; }
        public float bulletSpeed { get; set; }
        public float burnProb { get; set; }
        public float distTile { get; set; }
        public float splashArmorCoeff { get; set; }
        public float splashCubeSize { get; set; }
        public string[] ignoreClasses { get; set; }      
        public bool isBomb { get; set; }
    }

    public class WGTorpedo : WGProjectile
    {
        public int alertDist { get; set; }
        public float alphaDamage { get; set; }
        public float damage { get; set; }
        public string ammoType { get; set; }
        public float bulletDiametr { get; set; }
        public int maxDist { get; set; }
        public string[] ignoreClasses { get; set; }
        public float speed { get; set; }
        public float armingTime { get; set; }
        public float uwCritical { get; set; }
        public float visibilityFactor { get; set; }
        public float splashArmorCoeff { get; set; }
        public float splashCubeSize { get; set; }
    }


    public class WGBomb : WGProjectile
    {
        public bool affectedByPTZ { get; set; }
        public int alphaDamage { get; set; }
        public int alphaPiercingCS { get; set; }
        public int alphaPiercingHE { get; set; }
        public string ammoType { get; set; }
        public bool applyPTZCoeff { get; set; }
        public float bulletAirDrag { get; set; }
        public float bulletDetonator { get; set; }
        public float bulletDetonatorThreshold { get; set; }
        public float bulletDiametr { get; set; }
        public float bulletKrupp { get; set; }
        public float bulletMass { get; set; }
        public float bulletRicochetAt { get; set; }
        public float bulletAlwayRiccochetAt { get; set; }
        public float bulletSpeed { get; set; }
        public float burnProb { get; set; }
        public float distTile { get; set; }
        public string[] ignoreClasses { get; set; }
        public bool isBomb { get; set; }
        public float splashArmorCoeff { get; set; }
        public float splashCubeSize { get; set; }
    }

    public class WGDepthCharge : WGProjectile
    {
        public int alertDist { get; set; }
        public float alphaDamage { get; set; }
        public string ammoType { get; set; }
        public float burnProb { get; set; }
        public float uwCritical { get; set; }
        public float timer { get; set; }
        public float speed { get; set; }
        public float splashCubeSize { get; set; }
    }

    public class WGRocket : WGProjectile
    {
        public bool affectedByPTZ { get; set; }
        public float alphaDamage { get; set; }
        public int alphaPiercingCS { get; set; }
        public float alphaPiercingHE { get; set; }
        public string ammoType { get; set; }
        public bool applyPTZCoeff { get; set; }
        public float bulletAirDrag { get; set; }
        public float bulletDetonator { get; set; }
        public float bulletDetonatorThreshold { get; set; }
        public float bulletDiametr { get; set; }
        public float bulletKrupp { get; set; }
        public float bulletMass { get; set; }
        public float bulletRicochetAt { get; set; }
        public float bulletAlwayRiccochetAt { get; set; }
        public float bulletSpeed { get; set; }
        public float burnProb { get; set; }
        public float distTile { get; set; }
        public string[] ignoreClasses { get; set; }
        public bool isBomb { get; set; }
        public float splashArmorCoeff { get; set; }
        public float splashCubeSize { get; set; }
    }

}
