// <auto-generated />
using System.Collections.Generic;

namespace DataConverter.WGStructure
{

    public class WGShip
    {
        public Dictionary<string, ModuleArmaments> ModulesArmaments { get; set; }
        public Dictionary<string, ShipAbility> ShipAbilities { get; set; }
        public Dictionary<string, ShipUpgrades> ShipUpgradeInfo { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public int level { get; set; }
        public string name { get; set; }
        public Typeinfo typeinfo { get; set; }
    }

    public class ModuleArmaments { }

    #region Main battery
    public class MainBattery : ModuleArmaments
    {
        Dictionary<string, MainBatteryGun> guns { get; set; }
        public float maxDist { get; set; }
        public bool normalDistribution { get; set; } //not needed
        public float sigmaCount { get; set; }
    }

    public class MainBatteryGun
    {
        public string[] ammoList { get; set; }
        public float barrelDiameter { get; set; }
        public float[] horizSector { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public int numBarrels { get; set; }
        public float[] position { get; set; }
        public float[] rotationSpeed { get; set; }
        public float shotDelay { get; set; }
        public float smokePenalty { get; set; }
        public Typeinfo typeinfo { get; set; }
    }
    #endregion

    #region Fire Control
    public class FireControl : ModuleArmaments
    {
        public float maxDistCoef { get; set; }
        public float sigmaCountCoef { get; set; }
    }
    #endregion

    #region Torpedos
    public class TorpedoArray : ModuleArmaments
    {
        Dictionary<string, TorpedoLauncher> torpedoArray { get; set; }
    }

    public class TorpedoLauncher
    {
        public string[] ammoList { get; set; }
        public float barrelDiameter { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public string name { get; set; }
        public int numBarrels { get; set; }
        public float[] rotationSpeed { get; set; }
        public float shotDelay { get; set; }
        public float[] torpedoAngles { get; set; } //unknonw meaning, needed?
        public Typeinfo typeinfo { get; set; }
    }
    #endregion

    #region AntiAir and secondaries
    //this is AA and secondaries too. smallGun i think indicates if it's a secondary
    public class ATBA : ModuleArmaments
    {
        public AAAura AuraFar { get; set; }
        public AAAura AuraFar_Bubbles { get; set; }
        public Dictionary<string, AntiAirAndSecondaries> antiAirAndSecondaries { get; set; }
        public float maxDist { get; set; }
        public float sigmaCount { get; set; }
    }

    public class AntiAirAndSecondaries
    {
        public string[] ammoList { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public string name { get; set; }
        public int numBarrels { get; set; }
        public float[] rotationSpeed { get; set; }
        public float shotDelay { get; set; }
        public bool smallGun { get; set; }
        public Typeinfo typeinfo { get; set; }
    }

    #endregion

    #region Planes
    //actually useless
    public class AirArmament : ModuleArmaments
    {
        public int deckPlaceCount { get; set; }
        public int planesReserveCapacity { get; set; }
    }

    public class PlaneType : ModuleArmaments
    {
        public string planeType { get; set; }
    }
    #endregion

    #region Air Defense
    public class AirDefense
    {
        public AAAura AuraMedium { get; set; }
        public AAAura AuraNear { get; set; }
    }
    public class AAAura
    {
        public float areaDamage { get; set; }
        public float areaDamagePeriod { get; set; }
        public float bubbleDamage { get; set; }
        public float hitChance { get; set; }
        public int innerBubbleCount { get; set; }
        public float maxDistance { get; set; }
        public float minDistance { get; set; }
        public string type { get; set; }
    }

    #endregion

    #region DepthCharges
    public class DepthChargesArray : ModuleArmaments
    {
        Dictionary<string, DepthCharge> depthCharges { get; set; }
        public int maxPacks { get; set; }
        public float reloadTime { get; set; }
    }

    public class DepthCharge
    {
        public string[] ammoList { get; set; }
        public float[] horizSector { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public string name { get; set; }
        public int numBombs { get; set; }
        public float[] rotationSpeed { get; set; }
        public Typeinfo typeinfo { get; set; }
    }
    #endregion

    #region Engine
    public class Engine : ModuleArmaments
    {
        public float backwardEngineUpTime { get; set; }
        public float forwardEngineUpTime { get; set; }
        public float speedCoef { get; set; }
    }
    #endregion

    #region Hull
    public class Hull : ModuleArmaments
    {
        public float health { get; set; }
        public float maxSpeed { get; set; }
        public float rudderTime { get; set; }
        public float speedCoef { get; set; }
        public float visibilityCoefGKInSmoke { get; set; }
        public float visibilityFactor { get; set; }
        public float visibilityFactorByPlane { get; set; }
    }
    #endregion

    #region FlightControl
    //everything useless, again, except for squadrons
    public class FlightControl : ModuleArmaments
    {
        public AirsupportPlanesReserve airSupportPlanesReserve { get; set; }
        public object[] airSupportSquadrons { get; set; }
        public ConsumablePlanesReserve consumablePlanesReserve { get; set; }
        public object[] consumableSquadrons { get; set; }
        public bool hasConsumablePlanes { get; set; }
        public bool isGroundAttackEnabled { get; set; }
        public PlanesReserveAssignment planesReserveAssignment { get; set; }
        public float prepareTimeFactor { get; set; }
        public string[] squadrons { get; set; }
    }

    public class AirsupportPlanesReserve
    {
        public int Bomber { get; set; }
        public int Dive { get; set; }
        public int Fighter { get; set; }
        public int Skip { get; set; }
    }

    public class ConsumablePlanesReserve
    {
        public int Fighter { get; set; }
        public int Scout { get; set; }
    }

    public class PlanesReserveAssignment
    {
        public int Auxiliary { get; set; }
        public int Bomber { get; set; }
        public int Dive { get; set; }
        public int Fighter { get; set; }
        public int Scout { get; set; }
        public int Skip { get; set; }
    }
    #endregion

    #region Sub Pinger Gun
    public class PingerGun : ModuleArmaments
    {
        public float[] rotationSpeed { get; set; }
        public SectorParam[] sectorParams { get; set; }
        public float waveDistance { get; set; }
        public int waveHitAlertTime { get; set; }
        public int waveHitLifeTime { get; set; }
        public WaveParam[] waveParams { get; set; }
        public float waveReloadTime { get; set; }
    }

    public class SectorParam
    {
        public float alertTime { get; set; }
        public float lifetime { get; set; }
        public float width { get; set; }
        public float[][] widthParams { get; set; }
    }

    public class WaveParam
    {
        public float endWaveWidth { get; set; }
        public float energyCost { get; set; }
        public float startWaveWidth { get; set; }
        public float[] waveSpeed { get; set; }
    }

    #endregion

    #region Ship Consumable
    public class ShipAbility
    {
        public string[][] abils { get; set; }
        public int slot { get; set; }
    }
    #endregion

    #region Ship Upgrades and modules
    public class ShipUpgrades
    {
        public bool canBuy { get; set; }
        public Dictionary<string, string[]> components { get; set; }
        public object[] nextShips { get; set; }
        public string prev { get; set; }
        public string ucType { get; set; }
    }
    #endregion

}
