// <auto-generated />

using System;
using JsonSubTypes;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using WoWsShipBuilder.DataStructures;
using WoWsShipBuilder.DataStructures.Common;
using WoWsShipBuilder.DataStructures.Ship;

namespace DataConverter.WGStructure
{
    public class WGShip
    {
        public BurstArtilleryModule BurstArtilleryModule { get; set; }
        public Dictionary<string, ModuleArmaments> ModulesArmaments { get; set; }
        public Dictionary<string, ShipAbility> ShipAbilities { get; set; }
        public ShipUpgradeInfo ShipUpgradeInfo { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public int level { get; set; }
        public string name { get; set; }
        public string group { get; set; }
        public Typeinfo typeinfo { get; set; }
        public List<string> permoflages { get; set; }
    }

    [JsonConverter(typeof(JsonSubtypes))]
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(MainBattery), "guns")]
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(WgFireControl), "maxDistCoef")]
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(WgTorpedoArray), "torpedoArray")]
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(ATBA), "antiAirAndSecondaries")]
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(AirSupport), "maxPlaneFlightDist")]
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(AirDefense), "isAA")] 
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(WgDepthChargesArray), "depthCharges")]
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(WgEngine), "forwardEngineUpTime")]
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(WgHull), "visibilityFactor")]
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(WgFlightControl), "squadrons")]
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(WgPingerGun), "waveReloadTime")]
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(WgPlane), "planeType")]
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(WgSpecialAbility), "RageMode")]
    public class ModuleArmaments { }

    #region Main battery
    public class MainBattery : ModuleArmaments
    {
        public Dictionary<string, MainBatteryGun> guns { get; set; }
        public decimal maxDist { get; set; }
        public decimal sigmaCount { get; set; }
        public double taperDist { get; set; }
        
        public bool normalDistribution { get; set; }

        [JsonExtensionData]
        public Dictionary<string, JToken> AntiAirAuras { get; set; }

        [JsonIgnore]
        public Dictionary<string, AAAura> ConvertedAntiAirAuras
        {
            get => AntiAirAuras?.ToDictionary(entry => entry.Key, entry => entry.Value.ToObject<AAAura>()) ?? new Dictionary<string, AAAura>() ;
        }
    }

    public class MainBatteryGun
    {
        public string[] ammoList { get; set; }
        public decimal barrelDiameter { get; set; }
        public double[] horizSector { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public string name { get; set; }
        public int numBarrels { get; set; }
        public double[] position { get; set; }
        public decimal[] rotationSpeed { get; set; }
        public double[][] deadZone { get; set; }
        public decimal shotDelay { get; set; }
        public decimal smokePenalty { get; set; }
        public double idealRadius { get; set; }
        public double minRadius { get; set; }
        public double idealDistance { get; set; }
        public double radiusOnZero { get; set; }
        public double radiusOnDelim { get; set; }
        public double radiusOnMax { get; set; }
        public double delim { get; set; }
        public Typeinfo typeinfo { get; set; }

        public static explicit operator Gun(MainBatteryGun gun)
        {
            var newGun = new Gun(
                gun.ammoList.ToList(),
                gun.barrelDiameter,
                gun.id,
                gun.index,
                gun.name,
                gun.numBarrels,
                gun.rotationSpeed[0],
                gun.rotationSpeed[1],
                gun.shotDelay)
            {
                HorizontalSector = gun.horizSector,
                HorizontalDeadZones = gun.deadZone,
                HorizontalPosition = gun.position[1],
                VerticalPosition = gun.position[0],
                SmokeDetectionWhenFiring = gun.smokePenalty,
                WgGunIndex = gun.index,
            };
            newGun.TurretOrientation = newGun.VerticalPosition < 3 ? TurretOrientation.Forward : TurretOrientation.Backward;

            return newGun;
        }
    }
    #endregion

    #region Fire Control
    public class WgFireControl : ModuleArmaments
    {
        public decimal maxDistCoef { get; set; }
        public decimal sigmaCountCoef { get; set; }
    }
    #endregion

    #region Torpedos
    public class WgTorpedoArray : ModuleArmaments
    {
        public decimal timeToChangeAmmo { get; set; }
        public Dictionary<string, WgTorpedoLauncher> torpedoArray { get; set; }
    }

    public class WgTorpedoLauncher
    {
        public string[] ammoList { get; set; }
        public decimal barrelDiameter { get; set; }
        public decimal[][] deadZone { get; set; }
        public decimal[] horizSector { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public string name { get; set; }
        public int numBarrels { get; set; }
        public decimal[] rotationSpeed { get; set; }
        public decimal shotDelay { get; set; }
        public decimal[] torpedoAngles { get; set; } //unknonw meaning, needed?
        public Typeinfo typeinfo { get; set; }

        public static implicit operator TorpedoLauncher(WgTorpedoLauncher thisLauncher)
        {
            return new TorpedoLauncher(
                thisLauncher.ammoList.ToList(),
                thisLauncher.barrelDiameter,
                thisLauncher.id,
                thisLauncher.index,
                thisLauncher.name,
                thisLauncher.numBarrels,
                thisLauncher.rotationSpeed[0],
                thisLauncher.rotationSpeed[1],
                thisLauncher.shotDelay,
                thisLauncher.horizSector,
                thisLauncher.deadZone,
                thisLauncher.torpedoAngles);
        }
    }
    #endregion

    #region AntiAir and secondaries
    //this is AA and secondaries too. smallGun i think indicates if it's a secondary
    public class ATBA : ModuleArmaments
    {
        public Dictionary<string, AntiAirAndSecondaries> antiAirAndSecondaries { get; set; }
        public decimal maxDist { get; set; }
        public decimal sigmaCount { get; set; }
        [JsonExtensionData]
        public Dictionary<string, JToken> AntiAirData { get; set; }

        [JsonIgnore]
        public Dictionary<string, AAAura> ConvertedAntiAirData
        {
            get 
            {
                if (AntiAirData == null)
                {
                    return null;
                }
                else
                {
                    return AntiAirData.Select(entry => (entry.Key, entry.Value.ToObject<AAAura>()))
                           .Where(entry => entry.Item2 != null)
                           .ToDictionary(entry => entry.Key, entry => entry.Item2);
                } 
            } 
        }
    }

    public class AntiAirAndSecondaries
    {
        public string[] ammoList { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public string name { get; set; }
        public decimal barrelDiameter { get; set; }
        public int numBarrels { get; set; }
        public decimal[] rotationSpeed { get; set; }
        public decimal shotDelay { get; set; }
        public bool smallGun { get; set; }
        public Typeinfo typeinfo { get; set; }

        public static explicit operator Gun(AntiAirAndSecondaries wgSecondary)
        {
            return new Gun(
                wgSecondary.ammoList.ToList(),
                wgSecondary.barrelDiameter,
                wgSecondary.id,
                wgSecondary.index,
                wgSecondary.name,
                wgSecondary.numBarrels,
                wgSecondary.rotationSpeed[0],
                wgSecondary.rotationSpeed[1],
                wgSecondary.shotDelay
            );
        }
    }

    #endregion

    #region AirSupport

    /// <summary>
    /// Data for air strikes of ships.
    /// </summary>
    public class AirSupport : ModuleArmaments
    {
        public int chargesNum { get; set; }
        public decimal flyAwayTime { get; set; }
        public int maxDist { get; set; }
        public int maxPlaneFlightDist { get; set; }
        public int minDist { get; set; }
        public string planeName { get; set; }
        public decimal reloadTime { get; set; }
        public decimal timeBetweenShots { get; set; }
        public decimal timeFromHeaven { get; set; }
        
        public static implicit operator AirStrike(AirSupport thisAirSupport)
        {
            return new AirStrike(
                thisAirSupport.chargesNum,
                thisAirSupport.flyAwayTime,
                thisAirSupport.maxDist,
                thisAirSupport.maxPlaneFlightDist,
                thisAirSupport.minDist,
                thisAirSupport.planeName,
                thisAirSupport.reloadTime,
                thisAirSupport.timeBetweenShots,
                thisAirSupport.timeFromHeaven);
        }
    }

    #endregion

    #region Air Defense
    public class AirDefense : ModuleArmaments
    {
        public bool isAA { get; set; }

        [JsonExtensionData]
        public Dictionary<string, JToken> Auras { get; set; }

        [JsonIgnore]
        public Dictionary<string, AAAura> ConvertedAuras
        {
            get => Auras?.ToDictionary(entry => entry.Key, entry => entry.Value.ToObject<AAAura>()) ?? new Dictionary<string, AAAura>();
        }
    }
    public class AAAura
    {
        public decimal areaDamage { get; set; }
        public decimal areaDamagePeriod { get; set; }
        public decimal bubbleDamage { get; set; }
        public decimal hitChance { get; set; }
        public int innerBubbleCount { get; set; }
        public decimal maxDistance { get; set; }
        public decimal minDistance { get; set; }
        public string type { get; set; }

        public static implicit operator AntiAirAura(AAAura aura)
        {
            return new AntiAirAura(aura.hitChance, aura.maxDistance, aura.minDistance)
            {
                ConstantDps = aura.areaDamage,
                FlakDamage = aura.bubbleDamage,
                FlakCloudsNumber = aura.innerBubbleCount,
            };
        }
    }

    #endregion

    #region DepthCharges
    public class WgDepthChargesArray : ModuleArmaments
    {
        public Dictionary<string, WgDepthChargeLauncher> depthCharges { get; set; }
        public int maxPacks { get; set; }
        public decimal reloadTime { get; set; }
    }

    public class WgDepthChargeLauncher
    {
        public string[] ammoList { get; set; }
        public decimal[] horizSector { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public string name { get; set; }
        public int numBombs { get; set; }
        public decimal[] rotationSpeed { get; set; }
        public Typeinfo typeinfo { get; set; }

        public static implicit operator DepthChargeLauncher(WgDepthChargeLauncher wgLauncher)
        {
            return new DepthChargeLauncher(
                wgLauncher.ammoList.ToList(),
                wgLauncher.horizSector,
                wgLauncher.id,
                wgLauncher.index,
                wgLauncher.name,
                wgLauncher.numBombs,
                wgLauncher.rotationSpeed);
        }
    }
    #endregion

    #region Engine
    public class WgEngine : ModuleArmaments
    {
        public decimal backwardEngineUpTime { get; set; }
        public decimal forwardEngineUpTime { get; set; }
        public decimal speedCoef { get; set; }
        public HitLocationEngine HitLocationEngine { get; set; }
    }

    public class HitLocationEngine
    {
        public decimal armorCoeff { get; set; }
    }
    #endregion

    #region Hull
    public class WgHull : ModuleArmaments
    {
        public decimal health { get; set; }
        public decimal maxSpeed { get; set; }
        public decimal rudderTime { get; set; }
        public SteeringGear SG { get; set; }
        public decimal speedCoef { get; set; }
        public decimal visibilityCoefGKInSmoke { get; set; }
        public decimal visibilityFactor { get; set; }
        public decimal visibilityFactorByPlane { get; set; }
        public Dictionary<string, decimal> visibilityFactorsBySubmarine { get; set; }
        public decimal[][] burnNodes { get; set; } // Format: Fire resistance coeff, damage per second in %, burn time in s
        public decimal[][] floodNodes { get; set; } // Format: Torpedo belt reduction, damage per second in %, flood time in s
        public int turningRadius { get; set; }
        public decimal[] size { get; set; }
    }
    #endregion

    #region Steering Gear
    public class SteeringGear
    {
        public decimal armorCoeff { get; set; }
    }
    #endregion

    #region FlightControl
    public class WgFlightControl : ModuleArmaments
    {
        public string[] squadrons { get; set; }
    }

    public class WgPlane : ModuleArmaments
    {
        public string planeType { get; set; }
    }

    #endregion

    #region Sub Pinger Gun
    public class WgPingerGun : ModuleArmaments
    {
        public decimal[] rotationSpeed { get; set; }
        public WgSectorParam[] sectorParams { get; set; }
        public decimal waveDistance { get; set; }
        public int waveHitAlertTime { get; set; }
        public int waveHitLifeTime { get; set; }
        public WgWaveParam[] waveParams { get; set; }
        public decimal waveReloadTime { get; set; }

        public static implicit operator PingerGun(WgPingerGun thisWgPingerGun)
        {
            return new PingerGun(
                RotationSpeed: thisWgPingerGun.rotationSpeed,
                SectorParams: thisWgPingerGun.sectorParams.Select(wgSectorParam => (SectorParam)wgSectorParam).ToArray(),
                WaveDistance: thisWgPingerGun.waveDistance,
                WaveHitAlertTime: thisWgPingerGun.waveHitAlertTime,
                WaveHitLifeTime: thisWgPingerGun.waveHitLifeTime,
                WaveParams: thisWgPingerGun.waveParams.Select(wgWaveParam => (WaveParam)wgWaveParam).ToArray(),
                WaveReloadTime: thisWgPingerGun.waveReloadTime);
        }
    }

    public class WgSectorParam
    {
        public decimal alertTime { get; set; }
        public decimal lifetime { get; set; }
        public decimal width { get; set; }
        public decimal[][] widthParams { get; set; }

        public static implicit operator SectorParam(WgSectorParam thisSectorParam)
        {
            return new SectorParam(
                AlertTime: thisSectorParam.alertTime,
                Lifetime: thisSectorParam.lifetime,
                Width: thisSectorParam.width,
                WidthParams: thisSectorParam.widthParams
            );
        }
    }

    public class WgWaveParam
    {
        public decimal endWaveWidth { get; set; }
        public decimal energyCost { get; set; }
        public decimal startWaveWidth { get; set; }
        public decimal[] waveSpeed { get; set; }

        public static implicit operator WaveParam(WgWaveParam thisWaveParam)
        {
            return new WaveParam
            (
                EndWaveWidth: thisWaveParam.endWaveWidth,
                EnergyCost: thisWaveParam.energyCost,
                StartWaveWidth: thisWaveParam.startWaveWidth,
                WaveSpeed: thisWaveParam.waveSpeed
            );
        }
    }

    #endregion

    #region Ship Consumable
    public class ShipAbility
    {
        public string[][] abils { get; set; }
        public int slot { get; set; }
    }
    #endregion

    #region Ship Upgrades and modules

    public class ShipUpgradeInfo
    {
        public int costCR { get; set; }
        public int costGold { get; set; }
        public int costSaleGold { get; set; }
        public int costXP { get; set; }
        public int value { get; set; }
        [JsonExtensionData]
        public Dictionary<string, JToken> Upgrades { get; set; }

        [JsonIgnore]
        public Dictionary<string, ShipUpgrade> ConvertedUpgrades
        {
            get
            {
                return Upgrades.Select(entry => (entry.Key, entry.Value.ToObject<ShipUpgrade>())).ToDictionary(entry => entry.Key, entry => entry.Item2);
            }
        }
    }
    
    public class ShipUpgrade
    {
        public bool canBuy { get; set; }
        public Dictionary<string, string[]> components { get; set; }
        public string[] nextShips { get; set; }
        public string prev { get; set; }
        public string ucType { get; set; }
    }
    #endregion

    #region Special abilities of super ship
    public class BurstArtilleryModule
    {
        public decimal burstReloadTime { get; set; }
        public decimal fullReloadTime { get; set; }
        public Dictionary<string,float> modifiers { get; set; }
        public int shotsCount { get; set; }
    }

    public class WgSpecialAbility : ModuleArmaments
    {
        public RageMode RageMode { get; set; }
        public int buffsShiftMaxLevel { get; set; }
        public double buffsShiftSpeed { get; set; }
        public int buffsStartPool { get; set; }
        public Dictionary<string, float> modifiers { get; set; }
    }

    public class RageMode
    {
        public double boostDuration { get; set; }
        public int decrementCount { get; set; }
        public double decrementDelay { get; set; }
        public double decrementPeriod { get; set; }
        public int gunsForSalvo { get; set; }
        public Dictionary<string, float> modifiers { get; set; }
        public double radius { get; set; }
        public string rageModeName { get; set; }
        public int requiredHits { get; set; }
    }
    #endregion

}
