// <auto-generated />
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace GameParamsExtractor.WGStructure
{

    public class WGConsumable : WGObject
    {
        public long id { get; set; }
        public string index { get; set; }
        public string name { get; set; }
        public Dictionary<string,Statistics> variants { get; set; }
    }

    public class Statistics
    {
        public string descIDs { get; set; }
        public string group { get; set; }
        public string iconIDs { get; set; }
        public int numConsumables { get; set; }
        public float reloadTime { get; set; }
        public float workTime { get; set; }
        
        [JsonExtensionData]
        public Dictionary<string, JToken> RawModifiers { get; set; }

        [JsonIgnore]
        public Dictionary<string, float> Modifiers => RawModifiers
            ?.Where(x => x.Value.Type.Equals(JTokenType.Integer) || x.Value.Type.Equals(JTokenType.Float))
            ?.Select(entry => (entry.Key, Value: entry.Value.ToObject<float>()))
            ?.ToDictionary(entry => entry.Key, entry => entry.Value);
    }
        

}
