// <auto-generated />
using JsonSubTypes;
using Newtonsoft.Json;
using WowsShipBuilder.GameParamsExtractor.WGStructure;
using WowsShipBuilder.GameParamsExtractor.WGStructure.Ship;

namespace GameParamsExtractor.WGStructure
{
    [JsonConverter(typeof(JsonSubtypes), "typeinfo.type")]
    [JsonSubtypes.KnownSubType(typeof(WgConsumable), "Ability")]
    [JsonSubtypes.KnownSubType(typeof(WgAircraft), "Aircraft")]
    [JsonSubtypes.KnownSubType(typeof(WGCaptain), "Crew")]
    [JsonSubtypes.KnownSubType(typeof(WgExterior), "Exterior")]
    [JsonSubtypes.KnownSubType(typeof(WGModernization), "Modernization")]
    [JsonSubtypes.KnownSubType(typeof(WGProjectile), "Projectile")]
    [JsonSubtypes.KnownSubType(typeof(WgShip), "Ship")]
    [JsonSubtypes.KnownSubType(typeof(WGModule), "Unit")]
    public class WGObject
    {
        public TypeInfo typeinfo { get; set; }
    }

    public class TypeInfo
    {
        public string nation { get; set; }
        public string species { get; set; }
        public string type { get; set; }
    }

    public class ModifiersPerClass
    {
        public float AirCarrier { get; set; }
        public float Auxiliary { get; set; }
        public float Battleship { get; set; }
        public float Cruiser { get; set; }
        public float Destroyer { get; set; }
        public float Submarine { get; set; }
    }

}
