// <auto-generated />
using Newtonsoft.Json.Linq;

namespace GameParamsExtractor.WGStructure
{    public class WGExterior : WGObject
    {
        public long id { get; set; }
        public string index { get; set; }
        public Dictionary<string, JToken> modifiers { get; set; }
        public string name { get; set; }
        public int sortOrder { get; set; }
        public WGRestriction restrictions { get; set; }
        public int group { get; set; }
    }

    //check if they are actually string, couldn't find one example
    public class WGRestriction
    {
        public string[] forbiddenShips { get; set; }
        public string[] levels { get; set; }
        public string[] nations { get; set; }
        public string[] specificShips { get; set; }
        public string[] subtype { get; set; }
    }

}
