// <auto-generated />

using WowsShipBuilder.GameParamsExtractor.WGStructure;

namespace GameParamsExtractor.WGStructure
{
    public class WGModule : WgObject
    {
        public int costCR { get; set; }
        public int costXP { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public string name { get; set; }
    }

}
