// <auto-generated />
using Newtonsoft.Json.Linq;
using WowsShipBuilder.GameParamsExtractor.WGStructure;

namespace GameParamsExtractor.WGStructure
{
    public class WGModernization : WgObject
    {
        public string[] excludes { get; set; }
        public long id { get; set; }
        public string index { get; set; }
        public Dictionary<string, JToken> modifiers { get; set; }
        public string name { get; set; }
        public string[] nation { get; set; }
        public int[] shiplevel { get; set; }
        public string[] ships { get; set; }
        public string[] shiptype { get; set; }
        public int slot { get; set; }
        public int type { get; set; }
    }
}
